@extends('welcome')

@section('contenido')
<br>
    <div class="container">
        <h1 class="text-center">Términos y condiciones</h1>
            <ol>
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Bienvenido a Emprendimiento Social</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">En esta p&aacute;gina se exponen nuestros t&eacute;rminos de uso. Al usar Emprendimiento Social, acepta todas las normas enunciadas en la presente p&aacute;gina. En algunas de ellas no hemos tenido m&aacute;s remedio que utilizar un lenguaje jur&iacute;dico, no obstante, hemos hecho todo lo posible para ofrecer explicaciones claras y sencillas de lo que significa cada cosa, por medio de breves res&uacute;menes incluidos en recuadros azules como &eacute;ste. Se hace constar, sin embargo, que los res&uacute;menes no forman parte de los t&eacute;rminos legales oficiales. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Bienvenido a Emprendimiento Social. Al usar este sitio web (el "Sitio") y los servicios (junto con el Sitio, los "Servicios") ofrecidos por Emprendimiento Social,&nbsp; (junto con, representantes, consultores, empleados, y administradores, conjuntamente, "Emprendimiento Social", "nosotros" o "nos"), acepta las presentes normas legalmente vinculantes (los "T&eacute;rminos"). Igualmente acepta nuestra </span><a href="https://www.kickstarter.com/privacy"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Pol&iacute;tica de privacidad</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> y la </span><a href="https://www.kickstarter.com/cookies"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Pol&iacute;tica de cookies</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> y se compromete a seguir el resto de normas incluidas en el Sitio, como, por ejemplo, </span><a href="https://www.kickstarter.com/help/community"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Reglas de la comunidad</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> y </span><a href="https://www.kickstarter.com/rules"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">normas para iniciar proyectos</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Los presentes T&eacute;rminos podr&iacute;an ser objeto de actualizaci&oacute;n de tanto en tanto. En tal caso, comunicaremos cualquier cambio importante, mediante su publicaci&oacute;n en el Sitio o el env&iacute;o de un correo electr&oacute;nico. Las nuevas versiones de los t&eacute;rminos no tendr&aacute;n efectos retroactivos en ning&uacute;n caso, comunicaremos la fecha exacta de su entrada en vigor. Si sigue usando Emprendimiento Social tras la aplicaci&oacute;n de cualquier cambio, implicar&aacute; que acepta los nuevos t&eacute;rminos. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social va destinado a su uso personal, no comercial, salvo en los casos especificados en la </span><a href="https://www.kickstarter.com/terms-of-use#section4"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">secci&oacute;n 4</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> y la </span><a href="https://www.kickstarter.com/terms-of-use#sections5"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">secci&oacute;n 5</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">. </span></p>
                    <ol start="2">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Creaci&oacute;n de una cuenta</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Para registrarse y crear una cuenta en Emprendimiento Social, tendr&aacute; que ser mayor de 18 a&ntilde;os. El usuario ser&aacute; el responsable de su cuenta y de toda la actividad de la misma. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Podr&aacute; navegar por Emprendimiento Social sin registrarse para obtener una cuenta. No obstante, para usar algunas de sus funciones, ser&aacute; preciso registrarse, elegir un nombre de usuario y establecer una contrase&ntilde;a. Si lo hace, los datos que nos proporcione deber&aacute;n ser exactos y completos. No podr&aacute; suplantar la identidad de otra persona, ni elegir nombres ofensivos o que infrinjan derechos de terceros. El hecho de no atenerse a estas normas, podr&iacute;a suponer la cancelaci&oacute;n de su cuenta. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Responder&aacute; por toda la actividad de su cuenta y deber&aacute; mantener su contrase&ntilde;a en la confidencialidad. Si descubre que su cuenta ha sido utilizada sin su permiso, deber&aacute; denunciarlo mediante el env&iacute;o de un correo electr&oacute;nico a </span><a href="mailto:support@kickstarter.com"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">soporte@Emprendimiento Social.com</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">. </span></p>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Para crear una cuenta, tendr&aacute; que tener al menos 18 a&ntilde;os, o haber cumplido la edad legal para formalizar un contrato vinculante en su lugar de residencia. Si lo consideramos necesario, podr&iacute;amos solicitarle que acredite su edad. </span></p>
                    <ol start="3">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Actuaciones prohibidas</span></strong></li>
                    </ol>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Esta secci&oacute;n incluye una lista de actuaciones que probablemente ya sepa que no debe llevar a cabo, a saber, mentir, incumplir la ley, maltratar o insultar a otras personas, robar datos, acceder ilegalmente a los ordenadores de otras personas, etc. Comp&oacute;rtese correctamente y abst&eacute;ngase de realizar cualquiera de estos actos. </span></p>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Millones de personas utilizan Emprendimiento Social. Contamos con que se comporten de forma responsable y contribuyan a que Emprendimiento Social sea un entorno agradable. El uso del Sitio estar&aacute; sujeto a las siguientes normas: </span></p>
                    <ul>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No incumpla la ley.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Abst&eacute;ngase de realizar cualquier acci&oacute;n que infrinja o viole derechos de terceros, que incumpla la ley o cualquier contrato u obligaci&oacute;n legal frente a terceros. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No mienta.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> No publique informaci&oacute;n que le conste es falsa, enga&ntilde;osa o inexacta. Abst&eacute;ngase de llevar a cabo cualquier actuaci&oacute;n que resulte enga&ntilde;osa o fraudulenta. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No ofrezca art&iacute;culos prohibidos.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> No ofrezca recompensas ilegales, que violen cualquiera de las pol&iacute;ticas, normas o directrices de Emprendimiento Social, o que incumplan leyes o reglamentos en vigor. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No acose a nadie.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Abst&eacute;ngase de realizar cualquier actuaci&oacute;n que resulte amenazante, insultante, intimidatoria, difamatoria, calumniosa, dolosa, ofensiva, soez o que invada la privacidad de otra persona. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">&iexcl;No spam!</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Abst&eacute;ngase de distribuir material publicitario o promocional no solicitado o no autorizado, correo basura, correo no deseado o cadenas de mensajes. No ejecute listas de correo, listserv o cualquier tipo de servicio de respuesta autom&aacute;tica o correo electr&oacute;nico no deseado en el Sitio o a trav&eacute;s del mismo. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No da&ntilde;e ordenadores ajenos.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Abst&eacute;ngase de distribuir virus inform&aacute;ticos u otros elementos (c&oacute;digo, pel&iacute;culas, programas) concebidos para interferir en el correcto funcionamiento de cualquier software, hardware o equipo del Sitio (independientemente de que pertenezca a Emprendimiento Social o a un tercero). </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No use indebidamente los datos personales de otros usuarios.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Al usar Emprendimiento Social, y especialmente si crea un proyecto que logra la financiaci&oacute;n necesaria, es posible que reciba datos de otros usuarios, como sus nombres, direcciones de correo electr&oacute;nico y direcciones postales. Dichos datos se comunican con el &uacute;nico fin de participar en un proyecto de Emprendimiento Social: abst&eacute;ngase de usarlos con otros fines o de forma il&iacute;cita. </span></li>
                    </ul>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Tenemos que garantizar asimismo que el Sitio es seguro y nuestros sistemas funcionan correctamente. Por consiguiente, abst&eacute;ngase de realizar cualquiera de las acciones indicadas a continuaci&oacute;n, la mayor&iacute;a de las cuales vendr&iacute;an a decir "no ponga en peligro nuestro sistema". </span></p>
                    <ul>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No intente interferir en el correcto funcionamiento de los Servicios.</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Abst&eacute;ngase de eludir las medidas puestas en pr&aacute;ctica para proteger los Servicios.</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No intente da&ntilde;ar, ni acceder sin autorizaci&oacute;n a sistemas, datos, contrase&ntilde;as o cualquier otra informaci&oacute;n, independientemente de que pertenezcan a Emprendimiento Social o a un tercero.</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No realice ninguna actuaci&oacute;n que suponga una carga irrazonable para nuestra infraestructura o nuestros proveedores externos. </span><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">(Nos reservamos el derecho para determinar que es razonable).</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No use ning&uacute;n tipo de software ni dispositivo (ni manual ni autom&aacute;tico) para "rastrear" cualquier parte del Sitio.</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No desmonte, ni aplique t&eacute;cnicas de ingenier&iacute;a inversa a cualquier aspecto de Emprendimiento Social en un intento por acceder al c&oacute;digo fuente, las ideas subyacentes o los algoritmos, por ejemplo.</span></li>
                    </ul>
                    <ol start="4">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Funcionamiento de los proyectos</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">En la mayor&iacute;a de nuestros T&eacute;rminos de Uso se explica su relaci&oacute;n con Emprendimiento Social. Esta secci&oacute;n es diferente, puesto que expone la relaci&oacute;n <strong>entre creadores</strong> y <strong>inversores </strong>de los proyectos de Emprendimiento Social y las responsabilidades de cada uno de ellos. Se trata de los t&eacute;rminos que usted acepta al crear o patrocinar un proyecto de Emprendimiento Social. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social proporciona una plataforma de financiaci&oacute;n de proyectos creativos. Cuando un creador anuncia un proyecto en Emprendimiento Social est&aacute; invitando a otras personas a formalizar un contrato con &eacute;l. Quien decida patrocinar un proyecto est&aacute; aceptando la oferta del creador y, por tanto, celebrando dicho contrato. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social no es una de las partes del contrato. El contrato es un acuerdo jur&iacute;dico directo entre creadores y los inversores. A continuaci&oacute;n se exponen los t&eacute;rminos por los que se rige dicho acuerdo: </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Cuando un proyecto obtiene toda la financiaci&oacute;n que necesita, <strong>el creador ha de llevarlo a cabo y entregar todas las recompensas</strong>. Una vez realizadas dichas actuaciones, se entender&aacute; que el creador ha cumplido su obligaci&oacute;n frente a los inversores</span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">A lo largo de todo el proceso, los creadores deben a sus inversores el m&aacute;s alto nivel de esfuerzo, sinceridad en la comunicaci&oacute;n y dedicaci&oacute;n para lograr que el proyecto llegue a buen t&eacute;rmino. Al mismo tiempo, los inversores tienen que entender que al patrocinar un proyecto est&aacute;n ayudando a crear algo nuevo, no encargando algo que ya existe. Pueden producirse cambios o demoras, y existe la posibilidad de que ocurra algo que impida al creador terminar el proyecto seg&uacute;n lo prometido. </span></p>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Si un creador no pudiera finalizar su proyecto y entregar las recompensas, se considerar&aacute; que ha incumplido sus obligaciones fundamentales en virtud del presente acuerdo. Para remediar dicha situaci&oacute;n, el creador deber&aacute; hacer cuanto est&eacute; a su alcance para lograr la conclusi&oacute;n del proyecto m&aacute;s satisfactoria posible para los inversores Si un creador se encontrase en la situaci&oacute;n expuesta, a efectos de subsanarla y cumplir sus obligaciones ante los inversores, deber&aacute;: </span></p>
                    <ul>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">publicar una actualizaci&oacute;n en la que explique qu&eacute; se ha hecho, c&oacute;mo se han empleado los fondos y qu&eacute; le impide finalizar el proyecto seg&uacute;n lo previsto;</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">trabajar de forma diligente y de buena fe para lograr finalizar el proyecto de la forma m&aacute;s satisfactoria posible en el plazo comunicado a los inversores;</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">demostrar que ha empleado los fondos de forma adecuada y que ha realizado todos los esfuerzos posibles para finalizar el proyecto seg&uacute;n lo prometido;</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">ser sincero y abstenerse de realizar declaraciones falsas en sus comunicaciones a los inversores; y</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">ofrecer la devoluci&oacute;n de los fondos restantes (si los hubiere) a los inversores que no hayan recibido su recompensa (proporcionalmente a los importes que se hubieran comprometido a aportar) o explicarles c&oacute;mo se van a destinar esos fondos al finalizar el proyecto de otro modo.</span></li>
                    </ul>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">El creador es el &uacute;nico responsable de cumplir las promesas referentes a su proyecto. Si no pudiera cumplir los t&eacute;rminos del presente acuerdo, los inversores podr&iacute;an emprender acciones legales contra &eacute;l. </span></p>
                    <ol start="5">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Funcionamiento de la financiaci&oacute;n</span></strong></li>
                    </ol>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">En esta secci&oacute;n se expone en detalle lo relativo al patrocinio y la creaci&oacute;n de proyectos. Aspectos como el proceso de recaudaci&oacute;n de fondos, si es posible modificar o cancelar un compromiso de aportaci&oacute;n y c&oacute;mo pueden ponerse en contacto los creadores con los inversores para entregarles sus recompensas. </span></p>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">El <strong>patrocinio de un proyecto</strong> se rige por los siguientes t&eacute;rminos: </span></p>
                    <ul>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">El cargo s&oacute;lo se realiza si el proyecto alcanza su objetivo de financiaci&oacute;n.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Facilitar&aacute; sus datos de pago al asumir el compromiso de aportaci&oacute;n, pero no se efectuar&aacute; ning&uacute;n cargo. El cargo s&oacute;lo se realizar&aacute; si, al llegar la fecha l&iacute;mite de financiaci&oacute;n, el proyecto hubiera alcanzado su objetivo de captaci&oacute;n de fondos. Emprendimiento Social s&oacute;lo cobrar&aacute; el importe exacto que se ha comprometido a aportar. Si la campa&ntilde;a no alcanzase su objetivo de financiaci&oacute;n, no se efectuar&aacute; cargo alguno y no habr&aacute; ning&uacute;n intercambio monetario. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Posibilidad de reserva de fondos en tarjeta.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Emprendimiento Social y sus entidades de pago asociadas podr&iacute;an autorizar o reservar un cargo en su tarjeta de cr&eacute;dito (o el m&eacute;todo de pago utilizado por su parte) por un importe equivalente, como m&aacute;ximo, al de su compromiso de aportaci&oacute;n total, en cualquier momento entre la asunci&oacute;n de dicho compromiso y la recaudaci&oacute;n de los fondos. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Posibilidad de modificaci&oacute;n o cancelaci&oacute;n de compromiso de aportaci&oacute;n en cualquier momento antes de la fecha l&iacute;mite de financiaci&oacute;n del proyecto (con una excepci&oacute;n).</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Podr&aacute; aumentar, reducir o cancelar su compromiso de aportaci&oacute;n en cualquier momento a lo largo de la campa&ntilde;a, con una excepci&oacute;n: durante las &uacute;ltimas 24 horas de la campa&ntilde;a, no podr&aacute; reducir ni cancelar su compromiso de aportaci&oacute;n sin contactar antes con el departamento de atenci&oacute;n al cliente, en el supuesto de que dicha reducci&oacute;n o cancelaci&oacute;n pueda provocar que el proyecto no alcance su objetivo de financiaci&oacute;n. Una vez que el proyecto alcance la financiaci&oacute;n pretendida, para cancelar o modificar su compromiso de aportaci&oacute;n deber&aacute; contactar directamente con el creador para adoptar las medidas oportunas. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">La fecha de entrega prevista es una <em>estimaci&oacute;n</em> del creador.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> La fecha indicada en cada recompensa es la estimaci&oacute;n del creador sobre cu&aacute;ndo podr&aacute; entregarla, no una garant&iacute;a de cumplimiento de dicho plazo. El calendario podr&iacute;a cambiar a medida que el creador avance con el proyecto. Instamos a los creadores a pensarlo bien, a fijar una fecha que crean que van a poder cumplir sin problemas y a comunicar a los inversores cualquier cambio que se pueda producir. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Posibilidad de que el creador necesite informaci&oacute;n en relaci&oacute;n con las recompensas.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Para entregar las recompensas, el creador podr&iacute;a necesitar determinados datos de los inversores como, por ejemplo, su direcci&oacute;n postal o su talla de camiseta. Solicitar&aacute;n esos datos una vez finalizada con &eacute;xito la campa&ntilde;a. Para recibir la recompensa, deber&aacute; facilitarle los datos pertinentes en plazo razonable. Los creadores no deber&iacute;an solicitar datos personales que no resulten necesarios para la entrega de recompensas y no solicitar&aacute;n en ning&uacute;n caso datos sensibles como su n&uacute;mero de la Seguridad Social o datos de pago. Contacte con nosotros a trav&eacute;s de la direcci&oacute;n </span><a href="mailto:soporte@emprendimientoSocial.com"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">soporte@emprendimientoSocial.com</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> en caso de recibir una solicitud de informaci&oacute;n aparentemente inadecuada o excesiva. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social realiza reembolsos.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> La responsabilidad de finalizar un proyecto recae exclusivamente sobre su creador. Emprendimiento Social no conserva fondos en nombre de los creadores, no puede garantizar el trabajo de estos y no ofrece reembolsos. </span></li>
                    </ul>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">La <strong>creaci&oacute;n de un proyecto</strong> se rige por los siguientes t&eacute;rminos: </span></p>
                    <ul>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Posibilidad de reembolso de compromisos de aportaci&oacute;n si lo desea.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Una vez que el proyecto ha obtenido la financiaci&oacute;n necesaria, el creador podr&aacute; cancelar y reembolsar los compromisos de aportaci&oacute;n de los inversores en cualquier momento. Si lo hace, ya no tendr&aacute; ninguna obligaci&oacute;n ante dicho inversores y no existir&aacute; ning&uacute;n acuerdo entre ellos. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Cobro por Emprendimiento Social de comisi&oacute;n antes de transferencia de fondos en la cuenta del creador.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Emprendimiento Social y sus entidades de pago asociadas deducir&aacute;n sus comisiones antes de proceder a la transferencia de las ganancias de una campa&ntilde;a. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Posibilidad de que no puedan cobrarse algunos compromisos de aportaci&oacute;n, lo que podr&iacute;a reducir la financiaci&oacute;n obtenida.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Dado que existe la posibilidad de que algunos pagos no puedan cobrarse, por ejemplo si caduca la tarjeta de cr&eacute;dito de un inversores antes de que termine el plazo de financiaci&oacute;n y &eacute;ste no facilita informaci&oacute;n actualizada, Emprendimiento Social no puede garantizar que el importe de la financiaci&oacute;n recibida por el creador sea exactamente igual al importe &iacute;ntegro de los compromisos de aportaci&oacute;n menos las comisiones. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Asistencia en la resoluci&oacute;n de reclamaciones referentes a tarjetas de pago.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Si el inversor de un proyecto cuestionase el cargo ante la entidad emisora de su tarjeta, Emprendimiento Social se encargar&aacute; de defender el cargo ante dicha entidad, a efectos de resolver el conflicto. Acto seguido, notificar&aacute; la presentaci&oacute;n de la reclamaci&oacute;n al creador, para darle la oportunidad de aportar pruebas que ayuden a Emprendimiento Social a resolver el asunto a su favor. Si la reclamaci&oacute;n planteada por el titular de la tarjeta resultase ser leg&iacute;tima, el creador autoriza a Emprendimiento Social a cargar en la tarjeta de cr&eacute;dito facilitada por el creador al poner en marcha el proyecto el importe del cargo devuelto. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No construya castillos en el aire.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> No d&eacute; por sentado que va a poder poner en marcha su proyecto cuando quiera; cabe la posibilidad de que por alg&uacute;n motivo no podamos aceptarlo o que se produzca un problema que tarde en resolverse. No d&eacute; por hecho que va a poder cobrar la financiaci&oacute;n de forma inmediata; podr&iacute;a producirse una retraso entre la finalizaci&oacute;n con &eacute;xito de una campa&ntilde;a y el acceso del creador a los fondos. Por &uacute;ltimo, abst&eacute;ngase de tomar medidas que dependan del cobro de los fondos a cuya aportaci&oacute;n se hab&iacute;an comprometido los inversores hasta que realmente pueda retirarlos de su cuenta y gastarlos. </span></li>
                    </ul>
                    <ol start="6">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Qu&eacute; no hacemos y de qu&eacute; no somos responsables</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social no supervisa los proyectos y no media en las controversias entre usuarios. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social no responde por posibles da&ntilde;os o p&eacute;rdidas derivados del uso de los Servicios. No nos implicaremos en controversias entre usuarios, o entre usuarios y terceros referentes al uso de los Servicios. No supervisamos los resultados, ni la puntualidad de los proyectos, ni aprobamos el contenido que los usuarios presentan en el Sitio. Al usar los Servicios, exonera a Emprendimiento Social frente a cualesquiera reclamaciones, da&ntilde;os y perjuicios y demandas de todo tipo, conocidos o no, sospechados o no y comunicados o no, que traigan causa de o guarden relaci&oacute;n con las controversias mencionadas y los Servicios. El acceso a contenido a trav&eacute;s de los Servicios, corre por su cuenta y riesgo. Ser&aacute; el &uacute;nico responsable de los da&ntilde;os o p&eacute;rdidas irrogados como consecuencia de dicho acceso. </span></p>
                    <ol start="7">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Otros sitios web</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Si sigue un enlace con otro sitio web, lo que all&iacute; suceda no nos incumbe. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social puede incluir enlaces con otros sitios web, por ejemplo, las p&aacute;ginas de los proyectos, los perfiles de los usuarios y los comentarios pueden incluir enlaces con otros sitios web. Al acceder a sitios web de terceros, lo hace por su cuenta y riesgo. Emprendimiento Social no controla, ni aprueba dichos sitios. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social est&aacute; asociada con otras compa&ntilde;&iacute;as (como </span><a href="https://stripe.com/us/terms"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Stripe</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">) a efectos del procesamiento de pagos. Al patrocinar o crear un proyecto est&aacute; aceptando asimismo los t&eacute;rminos de servicio del procesador de pagos. </span></p>
                    <ol start="8">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Su propiedad intelectual</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No somos los propietarios del contenido que publica en Emprendimiento Social. No obstante, al hacerlo, nos est&aacute; dando permiso para usarlo o copiarlo si resulta necesario a efectos del funcionamiento del sitio o de mostrar lo que sucede en el mismo. Por lo general, s&oacute;lo usamos dicho material para promover proyectos y como escaparate de nuestra comunidad en el sitio web. Ser&aacute; responsable del contenido que publique y nos garantiza que su uso no entra&ntilde;ar&aacute; ning&uacute;n problema. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social no es la propietaria del contenido que publica ("Contenido"), pero necesitamos que nos conceda ciertas autorizaciones para poder prestar nuestros Servicios. Al presentar un proyecto para su revisi&oacute;n o al poner en marcha un proyecto, acepta los siguientes t&eacute;rminos: </span></p>
                    <ul>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Posibilidad de usar el Contenido presentado.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Nos concede, a nosotros y a quienes act&uacute;en en nuestro nombre, un derecho nacional, no exclusivo, a perpetuidad, irrevocable, exento de c&aacute;nones, susceptible de licencia y transmisible para usar, ejercer, comercializar y explotar los derechos de autor, publicidad, marcas y bases de datos inherentes al Contenido. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Posibilidad de introducir cambios (de edici&oacute;n o traducci&oacute;n, por ejemplo) al usar el Contenido.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Nos concede el derecho a editar, modificar, cambiar el formato, citar, eliminar o traducir cualquier parte del Contenido. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No enviar&aacute; material de cuyos derechos de autor no sea titular (a menos que tenga permiso para ello).</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Su Contenido no podr&aacute; incluir material de terceros protegido por derechos de autor, ni material sujeto a otros derechos patrimoniales de terceros, a menos que el titular leg&iacute;timo del material le haya dado permiso o que est&eacute; legalmente facultado para publicar el material (y conceder a Emprendimiento Social todos los derechos de licencia indicados). </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Los c&aacute;nones o derechos de licencia del Contenido son de su responsabilidad.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Deber&aacute; abonar todos los c&aacute;nones e importes adeudados a cualquier persona f&iacute;sica o jur&iacute;dica con respecto al Contenido o el alojamiento de dicho Contenido en Emprendimiento Social. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Garant&iacute;a de que si utilizamos el Contenido no estaremos infringiendo los derechos o derechos de autor de ning&uacute;n tercero.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Si Emprendimiento Social o sus usuarios explotasen o hiciesen uso del material presentado de conformidad con lo previsto en el presente acuerdo, garantiza que no infringiremos, ni vulneraremos ning&uacute;n derecho de terceros, incluidos, entre otros, derechos de protecci&oacute;n de datos de car&aacute;cter personal, derechos de publicidad, derechos de autor, derechos contractuales o cualquier otro derecho patrimonial o de propiedad intelectual. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Responsabilidad con respecto al material publicado.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Toda la informaci&oacute;n enviada al Sitio, mediante su publicaci&oacute;n o transmisi&oacute;n de forma privada, ser&aacute; responsabilidad exclusiva de la persona que haya creado el contenido en cuesti&oacute;n. </span></li>
                    <li><strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">No respondemos de posibles errores en el Contenido.</span></strong><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;"> Emprendimiento Social no responder&aacute; por posibles errores u omisiones del Contenido. </span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></li>
                    </ul>
                    <ol start="9">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Propiedad intelectual de Emprendimiento Social</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">El contenido de Emprendimiento Social est&aacute; protegido de distintas maneras. Tendr&aacute; derecho a usarlo para determinados fines personales, pero no para fines comerciales sin autorizaci&oacute;n previa. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Los servicios de Emprendimiento Social est&aacute;n legalmente protegidos de distintas maneras, a saber, mediante derechos de autor, marcas, marcas de servicio, patentes, secretos comerciales, as&iacute; como otros derechos y leyes. Se compromete a respetar todas las restricciones, informaci&oacute;n y avisos legales y sobre derechos de autor incluidos en cualquier contenido al que acceda a trav&eacute;s del Sitio. Se compromete asimismo a abstenerse de modificar, traducir o crear de cualquier otro modo obras derivadas del Servicio. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social le concede una licencia para reproducir contenido de los Servicios &uacute;nicamente para uso personal. Dicha licencia cubre tanto contenido protegido titularidad de Emprendimiento Social como contenido generado por los usuarios del Sitio. Se trata de una licencia mundial, no exclusiva, no susceptible de licencia y no transmisible. Si desea usar, reproducir, modificar, distribuir o almacenar dicho contenido con fines comerciales, tendr&aacute; que obtener la autorizaci&oacute;n previa por escrito de Emprendimiento Social o del titular pertinente de los derechos de autor. Por "fines comerciales" se entiende que tiene intenci&oacute;n de usar, vender, ceder bajo licencia, alquilar o explotar el contenido de cualquier otro modo para su uso comercial. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></p>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></p>
                    <ol start="10">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Gesti&oacute;n de problemas sobre derechos de autor</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">En Emprendimiento Social, cumplimos con la ONAPI. Para obtener m&aacute;s informaci&oacute;n sobre c&oacute;mo gestionamos las denuncias de infracciones de derechos de autor, consulte nuestra </span><a href="https://www.kickstarter.com/help/copyright"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Pol&iacute;tica de copyright</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">&nbsp;ONAPI (ley de Rep&uacute;blica Dominicana sobre derechos de autor en la era digital) establece una serie de requisitos legales para gestionar las denuncias de infracci&oacute;n de derechos de autor. En Emprendimiento Social cumplimos la DMCA y respondemos a las denuncias de presuntas infracciones si cumplen lo previsto en la ley y los requisitos enunciados en nuestra Pol&iacute;tica sobre Derechos de Autor. Nos reservamos el derecho de suprimir o desactivar contenido presuntamente infractor y de cancelar las cuentas de infractores reincidentes, si lo estimamos adecuado y a nuestra absoluta discreci&oacute;n. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Si desea denunciar una infracci&oacute;n de derechos de autor, consulte nuestra </span><a href="https://www.kickstarter.com/help/copyright"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Pol&iacute;tica de copyright</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">. El responsable de la tramitaci&oacute;n de las denuncias de presuntas infracciones de derechos de autor es: </span></p>
                    <p style="line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social<br />Attn: Grupo de trabajo.<br /></span><a href="mailto:Soporte@EmprendimientoSocial.com"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Soporte@EmprendimientoSocial.com</span></a></p>
                    <ol start="11">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Eliminaci&oacute;n de su cuenta </span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Podr&aacute; eliminar su cuenta en cualquier momento. Al eliminarla no se borrar&aacute; autom&aacute;ticamente el contenido publicado. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Para cancelar su cuenta bastar&aacute; con acceder a la configuraci&oacute;n de cuenta. Podr&iacute;amos conservar determinados datos exigidos legalmente o cuando sea necesario para fines comerciales leg&iacute;timos. Todas las estipulaciones del presente acuerdo subsistir&aacute;n a la cancelaci&oacute;n de la cuenta, incluidos nuestros derechos con respecto al contenido ya enviado al Sitio. Si, por ejemplo, ha puesto en marcha un proyecto, el hecho de cancelar su cuenta no supondr&aacute; la eliminaci&oacute;n inmediata del proyecto del Sitio). Si desea obtener informaci&oacute;n adicional o solicitar la eliminaci&oacute;n de la p&aacute;gina de un proyecto (esta opci&oacute;n no est&aacute; disponible en todos los casos), env&iacute;e un correo electr&oacute;nico a </span><a href="mailto:soporte@emprendimientoSocial.com"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">soporte@emprendimientoSocial.com</span></a><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">. </span></p>
                    <p style="text-align: justify; line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></strong></p>
                    <ol start="12">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Nuestros derechos</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Para poder funcionar, necesitamos mantener el control sobre todo lo que ocurre en el sitio web. Por dicho motivo, en esta secci&oacute;n nos reservamos el derecho de tomar decisiones destinadas a proteger la solidez e integridad de nuestro sistema. Nos tomamos estas facultades muy en serio, y solo las usaremos cuando no tengamos otra alternativa. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social se reserva los siguientes derechos: </span></p>
                    <ul>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Podremos introducir cambios en el Sitio y los Servicios de Emprendimiento Social sin previo aviso y sin incurrir en ning&uacute;n tipo de responsabilidad.</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Podremos decidir qui&eacute;n puede utilizar Emprendimiento Social. Podremos cancelar cuentas o negarnos a ofrecer nuestros Servicios, especialmente si se est&aacute; haciendo un mal uso de ellos. Podremos modificar nuestros criterios de idoneidad en cualquier momento. Si estas pr&aacute;cticas estuvieran prohibidas por la legislaci&oacute;n de su lugar de residencia, anularemos su derecho a usar Emprendimiento Social en dicha jurisdicci&oacute;n.</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Podremos cancelar cualquier compromiso de aportaci&oacute;n a un proyecto, en cualquier momento y por cualquier motivo.</span></li>
                    <li><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Podremos rechazar, cancelar, interrumpir, eliminar o suspender proyectos, en cualquier momento y por cualquier motivo.</span></li>
                    </ul>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Emprendimiento Social no responder&aacute; por los da&ntilde;os derivados de cualquiera de las actuaciones anteriores y tenemos la pol&iacute;tica de no comentar los motivos que nos han llevado a adoptar cualquiera de dichas medidas. </span></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif; color: red;">&nbsp;</span></strong></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif; color: red;">&nbsp;</span></strong></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif; color: red;">&nbsp;</span></strong></p>
                    <ol start="13">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Resoluci&oacute;n de conflictos y legislaci&oacute;n aplicable</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Nuestra sede est&aacute; en Santiago de los caballeros, por lo que cualquier controversia con nosotros se tramitar&aacute; en Santiago de los Caballeros, conforme a la ley de Rep&uacute;blica Dominicana</span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">En Emprendimiento Social le instamos a contactar con nosotros si tiene alg&uacute;n problema antes de acudir a los tribunales. Si lamentablemente se emprendiesen acciones legales, los presentes T&eacute;rminos (y el resto de normas, pol&iacute;ticas y reglas incorporados al presente acto por alusi&oacute;n) se regir&aacute;n por e interpretar&aacute;n de conformidad con la legislaci&oacute;n de Rep&uacute;blica Dominicana, sin dar cumplimiento a ning&uacute;n principio en materia de conflictos de ley, Acepta que Emprendimiento Social y sus Servicios son considerados un sitio web pasivo que no da origen a competencia sobre Emprendimiento Social ni sus matrices, empleados, administradores, ni espec&iacute;fica ni general, en ninguna jurisdicci&oacute;n distinta de la del Rep&uacute;blica Dominicana Acepta que los &uacute;nicos tribunales competentes para conocer de cualquier acci&oacute;n, en derecho o equidad, derivada de o que guarde relaci&oacute;n con los presentes T&eacute;rminos, o el uso o falta de uso por su parte de Emprendimiento Social ser&aacute;n los tribunales de Rep&uacute;blica Dominicana. Asimismo acepta y se somete a la competencia personal de dichos tribunales a efectos de la sustanciaci&oacute;n de cualquier acci&oacute;n de la naturaleza se&ntilde;alada. Renuncia irrevocablemente a cualquier derecho a su alcance con respecto a la celebraci&oacute;n de un juicio con jurado. </span></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></strong></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></strong></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></strong></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></strong></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></strong></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></strong></p>
                    <p style="line-height: normal;"><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;">&nbsp;</span></strong></p>
                    <ol start="14">
                    <li><strong><span style="font-size: 18.0pt; font-family: 'Times New Roman',serif;"> Miscel&aacute;nea</span></strong></li>
                    </ol>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Estas son nuestros t&eacute;rminos oficiales y las normas que regulan nuestro trabajo. Si le llegase informaci&oacute;n confusa o contradictoria con respecto a cualquiera de los aspectos tratados, consulte los presentes t&eacute;rminos, en &uacute;ltima instancia todo depende de ellos. Gracias por leerlos y por usar Emprendimiento Social. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Los presentes T&eacute;rminos, y el resto de material al que se hace referencia en los mismos, constituyen el acuerdo &iacute;ntegro entre usted y Emprendimiento Social con respecto a los Servicios. Dejan sin efecto a cualquier otra comunicaci&oacute;n y propuesta (verbal, escrita o electr&oacute;nica) entre Emprendimiento Social y usted en relaci&oacute;n con los Servicios y regular&aacute;n nuestra futura relaci&oacute;n. Si alguna cl&aacute;usula de los presentes T&eacute;rminos fuese declarada nula conforme a la legislaci&oacute;n aplicable, se proceder&aacute; a su eliminaci&oacute;n o limitaci&oacute;n, en la m&iacute;nima medida necesaria, de forma que el resto de T&eacute;rminos sigan en pleno vigor y resulten exigibles. La falta de ejercicio, por usted o por Emprendimiento Social de cualquier derecho contemplado en los presentes T&eacute;rminos no se entender&aacute; como una renuncia a cualesquiera otros derechos. </span></p>
                    <p style="text-align: justify; line-height: normal;"><span style="font-size: 12.0pt; font-family: 'Times New Roman',serif;">Los presentes T&eacute;rminos van destinados espec&iacute;ficamente al usuario. No podr&aacute;n ser cedidos, transmitidos ni cedidos bajo licencia sin la autorizaci&oacute;n previa por escrito de Emprendimiento Social. Emprendimiento Social tendr&aacute; derecho a ceder, transmitir y delegar cualquiera de los derechos y obligaciones que le corresponden en virtud de los presentes T&eacute;rminos sin su consentimiento. Le avisaremos por correo electr&oacute;nico, preaviso por escrito o mediante la publicaci&oacute;n de una notificaci&oacute;n visible en nuestro Sitio. </span></p>
                    <p style="text-align: center; line-height: normal;"><strong><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif;">FIN</span></strong></p>
                    <p>&nbsp;</p>
    </div>
@endsection